---
# tasks file for foreman_content_ceph

- name: "Vars | Include Ceph content vars"
  ansible.builtin.include_vars:
    dir: vars
    ignore_files:
      - "main.yml"
    extensions:
      - "yml"
    ignore_unknown_extensions: true

- name: "Vars | Append Ceph vars"
  ansible.builtin.set_fact:
    foreman_operatingsystems: "{{ foreman_operatingsystems | default([]) |
      union( foreman_operatingsystems_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"
    foreman_installation_media: "{{ foreman_installation_media | default([]) |
      union( foreman_installation_media_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"
    foreman_content_credentials: "{{ foreman_content_credentials | default([]) |
      union( foreman_content_credentials_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"
    foreman_products: "{{ foreman_products | default([]) |
      union( foreman_products_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"
    foreman_content_views: "{{ foreman_content_views | default([]) |
      union( foreman_content_views_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"
    foreman_activation_keys: "{{ foreman_activation_keys | default([]) |
      union( foreman_activation_keys_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"
    foreman_sync_plan_products: "{{ foreman_sync_plan_products | default([]) |
      union( foreman_sync_plan_products_ceph | default([]) if foreman_enable_ceph | bool else [] )
      }}"

