---

#######################################
### PRODUCT DEFAULTS
#######################################

# foreman_products_defaults_download_policy: on_demand
# foreman_products_defaults_mirroring_policy: mirror_complete
# foreman_products_defaults_verify_ssl_on_sync: false
# foreman_products_defaults_http_proxy_policy: global_default_http_proxy
# foreman_products_defaults_unprotected: false

### CEPH

# foreman_products_defaults_download_policy_ceph: "{{ foreman_products_defaults_download_policy }}"
# foreman_products_defaults_mirroring_policy_ceph: mirror_content_only
# foreman_products_defaults_verify_ssl_on_sync_ceph: "{{ foreman_products_defaults_verify_ssl_on_sync | bool }}"
# foreman_products_defaults_http_proxy_policy_ceph: "{{ foreman_products_defaults_http_proxy_policy }}"
# foreman_products_defaults_unprotected_ceph: "{{ foreman_products_defaults_unprotected | bool }}"

# foreman_products_defaults_download_policy_ceph_nautilus: "{{ foreman_products_defaults_download_policy_ceph }}"
# foreman_products_defaults_download_policy_ceph_octopus: "{{ foreman_products_defaults_download_policy_ceph }}"
# foreman_products_defaults_download_policy_ceph_pacific: "{{ foreman_products_defaults_download_policy_ceph }}"
# foreman_products_defaults_download_policy_ceph_quincy: "{{ foreman_products_defaults_download_policy_ceph }}"
# foreman_products_defaults_download_policy_ceph_reef: "{{ foreman_products_defaults_download_policy_ceph }}"
# foreman_products_defaults_download_policy_ceph_squid: "{{ foreman_products_defaults_download_policy_ceph }}"
# foreman_products_defaults_download_policy_ceph_docker: "{{ foreman_products_defaults_download_policy_ceph }}"

# foreman_products_defaults_mirroring_policy_ceph_nautilus: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
# foreman_products_defaults_mirroring_policy_ceph_octopus: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
# foreman_products_defaults_mirroring_policy_ceph_pacific: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
# foreman_products_defaults_mirroring_policy_ceph_quincy: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
# foreman_products_defaults_mirroring_policy_ceph_reef: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
# foreman_products_defaults_mirroring_policy_ceph_squid: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
# foreman_products_defaults_mirroring_policy_ceph_docker: "{{ foreman_products_defaults_mirroring_policy_ceph }}"

# foreman_products_defaults_verify_ssl_on_sync_ceph_nautilus: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
# foreman_products_defaults_verify_ssl_on_sync_ceph_octopus: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
# foreman_products_defaults_verify_ssl_on_sync_ceph_pacific: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
# foreman_products_defaults_verify_ssl_on_sync_ceph_quincy: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
# foreman_products_defaults_verify_ssl_on_sync_ceph_reef: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
# foreman_products_defaults_verify_ssl_on_sync_ceph_squid: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
# foreman_products_defaults_verify_ssl_on_sync_ceph_docker: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"

# foreman_products_defaults_http_proxy_policy_ceph_nautilus: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
# foreman_products_defaults_http_proxy_policy_ceph_octopus: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
# foreman_products_defaults_http_proxy_policy_ceph_pacific: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
# foreman_products_defaults_http_proxy_policy_ceph_quincy: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
# foreman_products_defaults_http_proxy_policy_ceph_reef: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
# foreman_products_defaults_http_proxy_policy_ceph_squid: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
# foreman_products_defaults_http_proxy_policy_ceph_docker: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"

# foreman_products_defaults_unprotected_ceph_nautilus: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
# foreman_products_defaults_unprotected_ceph_octopus: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
# foreman_products_defaults_unprotected_ceph_pacific: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
# foreman_products_defaults_unprotected_ceph_quincy: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
# foreman_products_defaults_unprotected_ceph_reef: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
# foreman_products_defaults_unprotected_ceph_squid: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
# foreman_products_defaults_unprotected_ceph_docker: "{{ foreman_products_defaults_unprotected_ceph | bool }}"
