---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-Ceph-release"
  download_policy: "{{ foreman_products_defaults_download_policy_ceph }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ceph | bool }}"

foreman_products_defaults_deb: &foreman_products_defaults_deb
  <<: *foreman_products_defaults
  content_type: deb
  mirroring_policy: "mirror_content_only"
  deb_components: main
  deb_architectures: amd64


foreman_products_defaults_ceph_quincy: &foreman_products_defaults_ceph_quincy
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ceph_quincy }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ceph_quincy }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph_quincy | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ceph_quincy }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ceph_quincy | bool }}"

foreman_products_defaults_ceph_quincy_deb: &foreman_products_defaults_ceph_quincy_deb
  <<: *foreman_products_defaults_deb
  content_type: deb
  download_policy: "{{ foreman_products_defaults_download_policy_ceph_quincy }}"
  mirroring_policy: "mirror_content_only"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph_quincy | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ceph_quincy }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ceph_quincy | bool }}"
  deb_components: main
  deb_architectures: amd64


foreman_products_ceph_quincy_el7:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_quincy_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Quincy - EL7"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-quincy-el7"
        <<: *foreman_products_defaults_ceph_quincy
        url: "{{ foreman_repo_baseurl_ceph_quincy_el7 }}/rpm-quincy/el7/x86_64/"
        organization: "{{ foreman_organization_ceph_quincy_el7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Quincy - EL7"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-noarch-quincy-el7"
        <<: *foreman_products_defaults_ceph_quincy
        url: "{{ foreman_repo_baseurl_ceph_quincy_el7 }}/rpm-quincy/el7/noarch"
        organization: "{{ foreman_organization_ceph_quincy_el7 }}"

foreman_products_ceph_quincy_el8:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_quincy_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Quincy - EL8"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-quincy-el8"
        <<: *foreman_products_defaults_ceph_quincy
        url: "{{ foreman_repo_baseurl_ceph_quincy_el8 }}/rpm-quincy/el8/x86_64/"
        organization: "{{ foreman_organization_ceph_quincy_el8 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Quincy - EL8"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-noarch-quincy-el8"
        <<: *foreman_products_defaults_ceph_quincy
        url: "{{ foreman_repo_baseurl_ceph_quincy_el8 }}/rpm-quincy/el8/noarch"
        organization: "{{ foreman_organization_ceph_quincy_el8 }}"

foreman_products_ceph_quincy_el9:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_quincy_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Quincy - EL9"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-quincy-el9"
        <<: *foreman_products_defaults_ceph_quincy
        url: "{{ foreman_repo_baseurl_ceph_quincy_el9 }}/rpm-quincy/el9/x86_64/"
        organization: "{{ foreman_organization_ceph_quincy_el9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Quincy - EL9"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-noarch-quincy-el9"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el9 }}/rpm-quincy/el9/noarch"
        organization: "{{ foreman_organization_ceph_quincy_el9 }}"

foreman_products_ceph_quincy_deb11:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_quincy_deb11 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Quincy - Debian 11 (Bullseye)"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-quincy-debian-bullseye"
        <<: *foreman_products_defaults_ceph_quincy_deb
        url: "{{ foreman_repo_baseurl_ceph_quincy_deb11 }}/debian-quincy/"
        deb_releases: bullseye
        organization: "{{ foreman_organization_ceph_quincy_deb11 }}"

foreman_products_ceph_quincy_ub2004:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_quincy_ub2004 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Quincy - Ubuntu 20.04 LTS (Focal Fossa)"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-quincy-ubuntu-focal"
        <<: *foreman_products_defaults_ceph_quincy_deb
        url: "{{ foreman_repo_baseurl_ceph_quincy_ub2004 }}/debian-quincy/"
        deb_releases: focal
        organization: "{{ foreman_organization_ceph_quincy_ub2004 }}"


foreman_content_views_ceph_quincy_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_quincy_el7"
    organization: "{{ foreman_organization_ceph_quincy_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Quincy - EL7"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Quincy - EL7"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_quincy_el7 }}"

foreman_content_views_ceph_quincy_el8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_quincy_el8"
    organization: "{{ foreman_organization_ceph_quincy_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Quincy - EL8"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Quincy - EL8"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_quincy_el8 }}"

foreman_content_views_ceph_quincy_el9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_quincy_el9"
    organization: "{{ foreman_organization_ceph_quincy_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Quincy - EL9"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Quincy - EL9"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_quincy_el9 }}"

foreman_content_views_ceph_quincy_deb11:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_quincy_deb11"
    organization: "{{ foreman_organization_ceph_quincy_deb11 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Quincy - Debian 11 (Bullseye)"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_quincy_deb11 }}"

foreman_content_views_ceph_quincy_ub2004:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_quincy_ub2004"
    organization: "{{ foreman_organization_ceph_quincy_ub2004 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Quincy - Ubuntu 20.04 LTS (Focal Fossa)"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_quincy_ub2004 }}"


foreman_content_credentials_ceph_quincy_main: []
foreman_content_credentials_ceph_quincy: "{{ ( foreman_content_credentials_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_products_ceph_quincy_main: []
foreman_products_ceph_quincy: "{{ ( foreman_products_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_products_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_products_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_products_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_products_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_products_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_content_views_ceph_quincy_main: []
foreman_content_views_ceph_quincy: "{{ ( foreman_content_views_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_content_views_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_operatingsystems_ceph_quincy_main: []
foreman_operatingsystems_ceph_quincy: "{{ ( foreman_operatingsystems_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_installation_media_ceph_quincy_main: []
foreman_installation_media_ceph_quincy: "{{ ( foreman_installation_media_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_activation_keys_ceph_quincy_main: []
foreman_activation_keys_ceph_quincy: "{{ ( foreman_activation_keys_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_sync_plan_products_ceph_quincy_main: []
foreman_sync_plan_products_ceph_quincy: "{{ ( foreman_sync_plan_products_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

