---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-Ceph-release"
  download_policy: "{{ foreman_products_defaults_download_policy_ceph }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ceph }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ceph }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ceph | bool }}"

foreman_products_defaults_deb: &foreman_products_defaults_deb
  <<: *foreman_products_defaults
  content_type: deb
  mirroring_policy: "mirror_content_only"
  deb_components: main
  deb_architectures: amd64


foreman_products_defaults_ceph_pacific: &foreman_products_defaults_ceph_pacific
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ceph_pacific }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ceph_pacific }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph_pacific | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ceph_pacific }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ceph_pacific | bool }}"

foreman_products_defaults_ceph_pacific_deb: &foreman_products_defaults_ceph_pacific_deb
  <<: *foreman_products_defaults_deb
  content_type: deb
  download_policy: "{{ foreman_products_defaults_download_policy_ceph_pacific }}"
  mirroring_policy: "mirror_content_only"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ceph_pacific | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ceph_pacific }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ceph_pacific | bool }}"
  deb_components: main
  deb_architectures: amd64


foreman_products_ceph_pacific_el7:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Pacific - EL7"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-el7"
        <<: *foreman_products_defaults_ceph_pacific
        url: "{{ foreman_repo_baseurl_ceph_pacific_el7 }}/rpm-pacific/el7/x86_64/"
        organization: "{{ foreman_organization_ceph_pacific_el7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Pacific - EL7"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-noarch-pacific-el7"
        <<: *foreman_products_defaults_ceph_pacific
        url: "{{ foreman_repo_baseurl_ceph_pacific_el7 }}/rpm-pacific/el7/noarch"
        organization: "{{ foreman_organization_ceph_pacific_el7 }}"

foreman_products_ceph_pacific_el8:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Pacific - EL8"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-el8"
        <<: *foreman_products_defaults_ceph_pacific
        url: "{{ foreman_repo_baseurl_ceph_pacific_el8 }}/rpm-pacific/el8/x86_64/"
        organization: "{{ foreman_organization_ceph_pacific_el8 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Pacific - EL8"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-noarch-pacific-el8"
        <<: *foreman_products_defaults_ceph_pacific
        url: "{{ foreman_repo_baseurl_ceph_pacific_el8 }}/rpm-pacific/el8/noarch"
        organization: "{{ foreman_organization_ceph_pacific_el8 }}"

foreman_products_ceph_pacific_el9:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Pacific - EL9"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-el9"
        <<: *foreman_products_defaults_ceph_pacific
        url: "{{ foreman_repo_baseurl_ceph_pacific_el9 }}/rpm-pacific/el9/x86_64/"
        organization: "{{ foreman_organization_ceph_pacific_el9 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Pacific - EL9"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-noarch-pacific-el9"
        <<: *foreman_products_defaults_ceph_pacific
        url: "{{ foreman_repo_baseurl_ceph_pacific_el9 }}/rpm-pacific/el9/noarch"
        organization: "{{ foreman_organization_ceph_pacific_el9 }}"

foreman_products_ceph_pacific_deb10:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_deb10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Debian 10 (Buster)"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-debian-buster"
        <<: *foreman_products_defaults_ceph_pacific_deb
        url: "{{ foreman_repo_baseurl_ceph_pacific_deb11 }}/debian-pacific/"
        deb_releases: buster
        organization: "{{ foreman_organization_ceph_pacific_deb10 }}"

foreman_products_ceph_pacific_deb11:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_deb11 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Debian 11 (Bullseye)"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-debian-bullseye"
        <<: *foreman_products_defaults_ceph_pacific_deb
        url: "{{ foreman_repo_baseurl_ceph_pacific_deb11 }}/debian-pacific/"
        deb_releases: bullseye
        organization: "{{ foreman_organization_ceph_pacific_deb11 }}"

foreman_products_ceph_pacific_ub1804:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_ub1804 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Ubuntu 18.04 LTS (Bionic Beaver)"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-ubuntu-bionic"
        <<: *foreman_products_defaults_ceph_pacific_deb
        url: "{{ foreman_repo_baseurl_ceph_pacific_ub2004 }}/debian-pacific/"
        deb_releases: bionic
        organization: "{{ foreman_organization_ceph_pacific_ub1804 }}"

foreman_products_ceph_pacific_ub2004:
  - name: "{{ foreman_product_name_prefix | default('') }}Ceph"
    label: "{{ foreman_product_label_prefix | default('') }}Ceph"
    organization: "{{ foreman_organization_ceph_pacific_ub2004 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Ubuntu 20.04 LTS (Focal Fossa)"
        label: "{{ foreman_repo_label_prefix | default('') }}ceph-pacific-ubuntu-focal"
        <<: *foreman_products_defaults_ceph_pacific_deb
        url: "{{ foreman_repo_baseurl_ceph_pacific_ub2004 }}/debian-pacific/"
        deb_releases: focal
        organization: "{{ foreman_organization_ceph_pacific_ub2004 }}"


foreman_content_views_ceph_pacific_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_el7"
    organization: "{{ foreman_organization_ceph_pacific_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Pacific - EL7"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Pacific - EL7"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_el7 }}"

foreman_content_views_ceph_pacific_el8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_el8"
    organization: "{{ foreman_organization_ceph_pacific_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Pacific - EL8"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Pacific - EL8"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_el8 }}"

foreman_content_views_ceph_pacific_el9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_el9"
    organization: "{{ foreman_organization_ceph_pacific_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for x86_64 - Pacific - EL9"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph noarch packages - Pacific - EL9"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_el9 }}"

foreman_content_views_ceph_pacific_deb10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_deb10"
    organization: "{{ foreman_organization_ceph_pacific_deb10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Debian 10 (Buster)"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_deb10 }}"

foreman_content_views_ceph_pacific_deb11:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_deb11"
    organization: "{{ foreman_organization_ceph_pacific_deb11 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Debian 11 (Bullseye)"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_deb11 }}"

foreman_content_views_ceph_pacific_ub1804:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_ub1804"
    organization: "{{ foreman_organization_ceph_pacific_ub1804 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Ubuntu 18.04 LTS (Bionic Beaver)"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_ub1804 }}"

foreman_content_views_ceph_pacific_ub2004:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}ceph_pacific_ub2004"
    organization: "{{ foreman_organization_ceph_pacific_ub2004 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Ceph packages for amd64 - Pacific - Ubuntu 20.04 LTS (Focal Fossa)"
        product: "{{ foreman_product_name_prefix | default('') }}Ceph"
    allow_promote: "{{ foreman_cv_allow_promote_ceph_pacific_ub2004 }}"


foreman_content_credentials_ceph_pacific_main: []
foreman_content_credentials_ceph_pacific: "{{ ( foreman_content_credentials_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_content_credentials_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

foreman_products_ceph_pacific_main: []
foreman_products_ceph_pacific: "{{ ( foreman_products_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_products_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_products_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_products_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_products_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_products_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_products_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_products_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

foreman_content_views_ceph_pacific_main: []
foreman_content_views_ceph_pacific: "{{ ( foreman_content_views_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_content_views_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_content_views_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_content_views_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_content_views_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_content_views_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_content_views_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_content_views_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

foreman_operatingsystems_ceph_pacific_main: []
foreman_operatingsystems_ceph_pacific: "{{ ( foreman_operatingsystems_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_operatingsystems_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

foreman_installation_media_ceph_pacific_main: []
foreman_installation_media_ceph_pacific: "{{ ( foreman_installation_media_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

foreman_activation_keys_ceph_pacific_main: []
foreman_activation_keys_ceph_pacific: "{{ ( foreman_activation_keys_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

foreman_sync_plan_products_ceph_pacific_main: []
foreman_sync_plan_products_ceph_pacific: "{{ ( foreman_sync_plan_products_ceph_pacific_main | default([]) if foreman_enable_ceph_pacific | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el7 | default([]) if foreman_enable_ceph_pacific_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el8 | default([]) if foreman_enable_ceph_pacific_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_el9 | default([]) if foreman_enable_ceph_pacific_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_deb10 | default([]) if foreman_enable_ceph_pacific_deb10 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_deb11 | default([]) if foreman_enable_ceph_pacific_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_ub1804 | default([]) if foreman_enable_ceph_pacific_ub1804 | bool else [] ) |
  union( foreman_installation_media_ceph_pacific_ub2004 | default([]) if foreman_enable_ceph_pacific_ub2004 | bool else [] )
  }}"

